### read all users
GET http://localhost:4000/user-api/users

### read users with projection
GET http://localhost:4000/user-api/user


### user authentication
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{
    "username" : "ravi",
    "password" : "ravi123"
}

### read user by ObjectId
GET http://localhost:4000/user-api/users/697dba7fc400871354c44fcd

### create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "username" : "ravi",
    "password" : "ravi123",
    "age" : 22
}

### update user by ObjectId
PUT http://localhost:4000/user-api/users/697dbcb848bd932b00d62aa5
Content-Type: application/json

{
    "username" : "anurag-updated",
    "password" : "anurag1234",
    "age" : 10
}

### delete user by ObjectId
DELETE http://localhost:4000/user-api/users/697dbcb848bd932b00d62aa5


###protected route
GET http://localhost:4000/user-api/test


### --------------
### create products
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "pid" : 200,
    "productName":"iphone",
    "price":900
}

###get all products
GET http://localhost:4000/product-api/products

### get product by id
GET http://localhost:4000/product-api/products/697dd01782a50662b216c38d

###update product by id
PUT http://localhost:4000/product-api/products/697dcd31bb921b2ab0c44e39
Content-Type: application/json

{
    "pid":100,
    "productName":"gelpen",
    "price":25
}