###create products
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
    "productName":"QuietComfort Ultra",
    "price":50000,
    "brand":"Bose"
}

###get the products
GET http://localhost:4000/product-api/products 


###create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name":"raju",
    "email":"raju@gmail.com",
    "password":"raju123",
    "cart":[]
}

### req to add product to cart
PUT http://localhost:4000/user-api/user-cart/userid/6981939307fad377ca2b6f0c/productid/698067336450cf369e5f0a4a


###read the cart details
GET http://localhost:4000/user-api/users/6981939307fad377ca2b6f0c